export interface JKT48Member {
  name: string;
  gen: string;
  photo: string;
}

export const JKT48_MEMBERS: JKT48Member[] = [
  { name: "Feni", gen: "Gen 3", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/feni_fhaxti.jpg" },
  { name: "Gita", gen: "Gen 6", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/gita_sekar_andarini_nvca0n.jpg" },
  { name: "Christy", gen: "Gen 7", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/christy_rjiaw6.jpg" },
  { name: "Eli", gen: "Gen 7", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/helisma_putri_ayw3hg.jpg" },
  { name: "Jessi", gen: "Gen 7", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/jessi_o3cdyg.jpg" },
  { name: "Freya", gen: "Gen 7", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/freya_jayawardana_mzdjf0.jpg" },
  { name: "Muthe", gen: "Gen 7", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/muthe_x8rj6m.jpg" },
  { name: "Olla", gen: "Gen 7", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/febriola_sinambela_pg6fzb.jpg" },
  { name: "Fiony", gen: "Gen 8", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/fiony_mjbodf.jpg" },
  { name: "Lulu", gen: "Gen 8", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/lulu_cpoakv.jpg" },
  { name: "Oniel", gen: "Gen 8", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/oniel_imjae9.jpg" },
  { name: "Indah", gen: "Gen 9", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/indah_ltaxxn.jpg" },
  { name: "Kathrina", gen: "Gen 9", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/kathrina_ex91yn.jpg" },
  { name: "Marsha", gen: "Gen 9", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/marsha_lenathea_iqu1d1.jpg" },
  { name: "Lia", gen: "Gen 10", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/lia_dotnos.jpg" },
  { name: "Ella", gen: "Gen 10", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/gabriela_abigail_ui1hmv.jpg" },
  { name: "Lyn", gen: "Gen 10", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/jesslyn_elly_qoehzs.jpg" },
  { name: "Raisha", gen: "Gen 10", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/raisha_g85ajn.jpg" },
  { name: "Alya", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/alya_cfy2dy.jpg" },
  { name: "Anindya", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/anindya_elmsrh.jpg" },
  { name: "Cathy", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/cathy_swseqw.jpg" },
  { name: "Chelsea", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/chelsea_davina_r0rvqy.jpg" },
  { name: "Cynthia", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/cynthia_adcpdu.jpg" },
  { name: "Daisy", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/daisy_bjn1de.jpg" },
  { name: "Danella", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/danella_rg4dux.jpg" },
  { name: "Elin", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/elin_ni6m5z.jpg" },
  { name: "Gendis", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/gendis_c7hrct.jpg" },
  { name: "Gracie", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/gracie_vv4pap.jpg" },
  { name: "Greesel", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/greesella_adhalia_fksjuw.jpg" },
  { name: "Michie", gen: "Gen 11", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/michie_cz97cu.jpg" },
  { name: "Aralie", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/aralie_n6q3xd.jpg" },
  { name: "Delynn", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/adeline_wijaya_sfccz6.jpg" },
  { name: "Erine", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/erine_s6rhtf.jpg" },
  { name: "Fritzy", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/fritzy_odug7q.jpg" },
  { name: "Kimmy", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/kimmy_vln9ki.jpg" },
  { name: "Lana", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/lana_ztoaoe.jpg" },
  { name: "Levi", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/levi_azukkk.jpg" },
  { name: "Lily", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/lily_jqskyy.jpg" },
  { name: "Nachia", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/nina_tutachia_sfhyvw.jpg" },
  { name: "Nala", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/shabilqis_naila_lsb03z.jpg" },
  { name: "Nayla", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/nayla_fi8vk4.jpg" },
  { name: "Oline", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/oline_manuel_uceo33.jpg" },
  { name: "Ribka", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/ribka_qfrppk.jpg" },
  { name: "Trisha", gen: "Gen 12", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/trisha_tobmvw.jpg" },
  { name: "Auwia", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/auwia_z2klqc.jpg" },
  { name: "Ekin", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/ekin_ebmyq2.jpg" },
  { name: "Giaa", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/giaa_octhox.jpg" },
  { name: "Intan", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/intan_mo0nll.jpg" },
  { name: "Jemima", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/jemima_jzbqy5.jpg" },
  { name: "Maira", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/maira_ajatfp.jpg" },
  { name: "Mikaela", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/mikaela_p0wmji.jpg" },
  { name: "Rilly", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/rilly_dfero7.jpg" },
  { name: "Virgi", gen: "Gen 13", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/virgi_psoymy.jpg" },
  { name: "Bella", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/bella_rgmvb4.jpg" },
  { name: "Carissa", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/carissa_t62we1.jpg" },
  { name: "Fahira", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/fahira_jkvrpl.jpg" },
  { name: "Fera", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/fera_jj8swk.jpg" },
  { name: "Heidi", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/heidi_ltllch.jpg" },
  { name: "Jazzy", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/jazzy_w6xbp0.jpg" },
  { name: "Maxine", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/jazzy_w6xbp0.jpg" },
  { name: "Ralyne", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/ralyne_l6vtcc.jpg" },
  { name: "Rara", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/rara_dxomqh.jpg" },
  { name: "Sona", gen: "Gen 14", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/sona_sdepst.jpg" },
  { name: "Isha", gen: "JKT48V", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/isha_dafnfr.jpg" },
  { name: "Maura", gen: "JKT48V", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/maura_enryqr.jpg" },
  { name: "Pia", gen: "JKT48V", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/pia_q9nswa.jpg" },
  { name: "Sami", gen: "JKT48V", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/sami_ybdjge.jpg" },
  { name: "Tana", gen: "JKT48V", photo: "https://res.cloudinary.com/dak2dhea9/image/upload/tana_h0eqec.jpg" },
];